### ISSUE TITLE
NoMethodError: undefined method `customer_id=' for #<Plaid::Client:0x0000000003e166a0 @client_id=nil, @secret=nil>

### ISSUE THREAD

**Issue by sarink** [cdwilhelm/plaid_rails#1]
I'm on a vanilla Rails 5 API-only application

When running `rake db:migrate` the following error is presented:
```
NoMethodError: undefined method `customer_id=' for #<Plaid::Client:0x0000000003e166a0 @client_id=nil, @secret=nil>
```

Update: It looks like the plaid gem has been updated to v4, but this engine uses v3. To use v3 (and probably make this engine work) we have to use the [plaid-ruby-legacy](https://github.com/plaid/plaid-ruby-legacy) gem instead.

**Comment by cdwilhelm** [comment]
@sarink 
Sorry for not responding to this.  I'm working on an update to support the plaid-ruby 6.0 and new Link api.  Look for a new gem version in the next week or so.

**Comment by cdwilhelm** [comment]
Version 0.11.0 supports the new plaid api
